COUNTRY = [
    'CANADA',
    'FEDERAL JURISDICTION',
    'PROVINCES AND TERRITORIES',
]


PROVINCE = [
    'ALBERTA',
    'BRITISH COLUMBIA',
    'MANITOBA',
    'NEW BRUNSWICK',
    'NEWFOUNDLAND AND LABRADOR',
    'NORTHWEST TERRITORIES',
    'NORTHWEST TERRITORIES INCLUDING NUNAVUT',
    'NOVA SCOTIA',
    'NUNAVUT',
    'ONTARIO',
    'PRINCE EDWARD ISLAND',
    'QUEBEC',
    'SASKATCHEWAN',
    'YUKON',
]


REGION = [
    'ATLANTIC REGION',
    'ONTARIO REGION',
    'PACIFIC REGION',
    'PRAIRIE REGION',
    'QUEBEC REGION',
]


FEDERAL_REGION_MAP = {
    'ATLANTIC REGION': [
        'NEW BRUNSWICK',
        'NEWFOUNDLAND AND LABRADOR',
        'NOVA SCOTIA',
        'PRINCE EDWARD ISLAND',
    ],
    'ONTARIO REGION': [
        'NUNAVUT',
        'ONTARIO',
    ],
    'PACIFIC REGION': [
        'BRITISH COLUMBIA',
        'YUKON',
    ],
    'PRAIRIE REGION': [
        'ALBERTA',
        'SASKATCHEWAN',
        'MANITOBA',
        'NORTHWEST TERRITORIES',
    ],
    'QUEBEC REGION': [
        'QUEBEC'
    ],
}
